spring.datasource.url=jdbc:postgresql://localhost:5432/arrochaono
spring.datasource.username=postgres
spring.datasource.password=6603

# Outras configurações
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081
